# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a Node.js base image
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript source
RUN npm run build

# Final stage: production image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the built files from the build stage
COPY --from=build /app/build ./build

# Copy package.json and package-lock.json for production
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Set the entry point to run the server
ENTRYPOINT ["node", "build/index.js"]
